Repository rubygarage/inquisition, pull requests merged in 2019-07, with the labels that each got.

#49 PEO-308 Fix CI build
  .circleci/config.yml
Labels: BUGFIX, REVIEWED

#47 PEO-277 Create a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: NEED REVIEW, ✓ DK, ✓ RY

#44 PEO-300 Cleanup source code
  .circleci/config.yml
  .gitignore
  .reeks.yml
  .travis.yml
  Gemfile.lock
  inquisition.gemspec
  lib/inquisition/auditors/backend/bullet/outputer.rb
  lib/inquisition/auditors/backend/haml_lint/outputer.rb
  lib/inquisition/auditors/backend/railroady/outputer.rb
  lib/inquisition/auditors/backend/rails_erd/outputer.rb
  lib/inquisition/auditors/backend/rubocop_rspec/outputer.rb
  lib/inquisition/auditors/backend/simplecov/outputer.rb
  lib/inquisition/auditors/backend/slim_lint/outputer.rb
  lib/inquisition/core/presenters/elements/html/static/chart/route_methods_chart_presenter.rb
  lib/inquisition/generators/html/assets/js/DateJS/build/i18n/sa-IN.js
  lib/inquisition/tasks/inquisition.rake
Labels: BUGFIX, REVIEWED

#46 PEO-303 Setup integration with code climate
  .circleci/config.yml
  .codeclimate.yml
Labels: FEATURE, NEED REVIEW

#51 Remove require execjs
  lib/inquisition/core/presenters/data/common/javascript_runtime_version_presenter.rb
Labels: HOTFIX, NEED REVIEW

#50 PEO-304 Error classes
  lib/inquisition/authorization.rb
  lib/inquisition/core/checkers/additional_software_checker.rb
  lib/inquisition/core/checkers/exist_file_checker.rb
  lib/inquisition/core/checkers/gem_checker.rb
  lib/inquisition/core/checkers/ruby_version_checker.rb
  lib/inquisition/error.rb
  lib/inquisition/errors/additional_software_absence_error.rb
  lib/inquisition/errors/base_config_absense_error.rb
  lib/inquisition/errors/base_error.rb
  lib/inquisition/errors/invalid_ruby_version_error.rb
  lib/inquisition/errors/no_config_file_error.rb
  lib/inquisition/errors/no_gem_error.rb
  spec/inquisition/authorization_spec.rb
  spec/inquisition/cli_spec.rb
  spec/inquisition/configure_spec.rb
  spec/inquisition/core/checkers/additional_software_checker_spec.rb
  spec/inquisition/core/checkers/exist_file_checker_spec.rb
  spec/inquisition/core/checkers/gem_checker_spec.rb
  spec/inquisition/core/checkers/ruby_version_checker_spec.rb
  spec/inquisition/core/configurers/update_file_configure_spec.rb
  spec/inquisition/errors/base_error_spec.rb
Labels: FEATURE, NEED REVIEW

#52 PEO-309 Update rubocop
  .codeclimate.yml
  .reek.yml
  .rubocop.yml
  config.reek
  inquisition.gemspec
  lib/inquisition/core/presenters/elements/html/static/menu/menu_items_presenter.rb
  lib/inquisition/generators/html/assets/js/DateJS/build/i18n/sk-SK.js
  spec/support/matchers/matcher_with_output_message.rb
Labels: FEATURE, NEED REVIEW

#54 PEO-299 Remove the division into <Backend> and <Frontend>
  lib/inquisition/auditors/backend/i18n_tasks/formatter.rb
  lib/inquisition/auditors/backend/i18n_tasks/installer.rb
  lib/inquisition/auditors/backend/i18n_tasks/runner.rb
  lib/inquisition/auditors/backend/installer.rb
  lib/inquisition/auditors/backend/runner.rb
  lib/inquisition/auditors/frontend/installer.rb
  lib/inquisition/auditors/frontend/runner.rb
  lib/inquisition/configure.rb
  lib/inquisition/runner.rb
  spec/inquisition/auditors/frontend/installer_spec.rb
  spec/inquisition/configure_spec.rb
Labels: FEATURE, NEED REVIEW

#56 PEO-302 Update circleci configuration
  .circleci/config.yml
  inquisition.gemspec
Labels: FEATURE, REVIEWED

#61 PEO-318 Implement Brakeman runner
  inquisition.gemspec
  lib/inquisition/brakeman/runner.rb
  lib/inquisition/issue.rb
  spec/inquisition/brakeman/runner_spec.rb
Labels: FEATURE, REVIEWED

#63 PEO-341 Implement active_record_doctor runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/runner.rb
  lib/inquisition/runner.rb
  spec/inquisition/active_record_doctor/runner_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SN, ✓ SS

#67 PEO-349 Implement rubocop runner
  config/.rubocop.yml
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/rubocop/rubocop_modified_runner.rb
  lib/inquisition/rubocop/runner.rb
  spec/inquisition/rubocop/rubocop_modified_runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
Labels: FEATURE, REVIEWED, ✓ SN, ✓ SS

#62 PEO-319 Implement Bundler Audit runner
  .rubocop.yml
  inquisition.gemspec
  lib/inquisition/bundler/audit/runner.rb
  spec/inquisition/bundler/audit/runner_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SN, ✓ SS

#64 PEO-342 Implement LolDba runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/lol_dba/runner.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/spec_helper.rb
Labels: FEATURE, NEED REVIEW, ✓ SN, ✓ SS

#66 PEO-350 Implement fasterer runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/fasterer/runner.rb
  spec/inquisition/fasterer/runner_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SN, ✓ SS

#68 PEO-352 Implement rails_best_practices runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/issue.rb
  lib/inquisition/rails_best_practices/runner.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SN, ✓ SS

#69 PEO-351 Implement rubycritic runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/rubycritic/analysers/flay.rb
  lib/inquisition/rubycritic/analysers/flog.rb
  lib/inquisition/rubycritic/analysers/reek.rb
  lib/inquisition/rubycritic/runner.rb
  spec/inquisition/rubycritic/analysers/flay_spec.rb
  spec/inquisition/rubycritic/analysers/flog_spec.rb
  spec/inquisition/rubycritic/analysers/reek_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SS

#70 PEO-353 Implement traceroute runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/traceroute/runner.rb
  spec/inquisition/traceroute/runner_spec.rb
Labels: FEATURE, NEED REVIEW

#74 PEO-317 Update structure
  .reek.yml
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/runner.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/cli.rb
  lib/inquisition/collector.rb
  lib/inquisition/configuration.rb
  lib/inquisition/logger.rb
  lib/inquisition/plugin.rb
  lib/inquisition/rails_best_practices/runner.rb
  lib/inquisition/runner.rb
  lib/inquisition/traceroute/runner.rb
  lib/inquisition/version.rb
  spec/inquisition/collector_spec.rb
  spec/inquisition/configuration_spec.rb
  spec/inquisition/logger_spec.rb
  spec/inquisition/plugin_spec.rb
  spec/inquisition/version_spec.rb
  spec/inquisition_spec.rb
Labels: NEED REVIEW, ✓ DK, ✓ RY
