Repository rubygarage/inquisition, pull requests merged in 2019-09, with the labels that each got.

#85 PEO-357 Add output bar about success or failed runner
  .reek.yml
  .rubocop.yml
  lib/inquisition.rb
  lib/inquisition/collector.rb
  lib/inquisition/configuration.rb
  lib/inquisition/executor.rb
  lib/inquisition/fanout.rb
  lib/inquisition/options.rb
  lib/inquisition/outputter.rb
  lib/inquisition/outputter/html.rb
  lib/inquisition/outputter/progress.rb
  lib/inquisition/runner.rb
  lib/inquisition/tasks/inquisition.rake
  spec/inquisition/collector_spec.rb
  spec/inquisition/configuration_spec.rb
  spec/inquisition/executor_spec.rb
  spec/inquisition/fanout_spec.rb
  spec/inquisition/options_spec.rb
  spec/inquisition/outputter/html_spec.rb
  spec/inquisition/outputter/progress_spec.rb
  spec/inquisition/outputter_spec.rb
  spec/inquisition/runner_spec.rb
  spec/inquisition/tasks/inquisition_spec.rb
  spec/spec_helper.rb
Labels: FEATURE, NEED REVIEW

#105 PEO-481 Add missing E2E tests
  lib/inquisition/rubycritic/runner.rb
  spec/dummy/app/models/application_record.rb
  spec/dummy/spec/factories/factory_1.rb
  spec/dummy/spec/factories/factory_2.rb
  spec/fixtures/files/factory_bot.yml
  spec/fixtures/files/rubycritic.yml
  spec/integration/factory_bot/runner_spec.rb
Labels: FEATURE, REVIEWED

#106 PEO-357 Pass payload to outputter
  lib/inquisition/collector.rb
  lib/inquisition/fanout.rb
  lib/inquisition/outputter/html.rb
  lib/inquisition/outputter/progress.rb
  spec/inquisition/collector_spec.rb
  spec/inquisition/executor_spec.rb
  spec/inquisition/fanout_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/outputter/progress_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/rubocop_modified_runner_spec.rb
  spec/inquisition/rubycritic/analysers/flay_spec.rb
  spec/inquisition/rubycritic/analysers/flog_spec.rb
  spec/inquisition/rubycritic/analysers/reek_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/spec_helper.rb
Labels: BUGFIX, NEED REVIEW, ✓ DK

#103 PEO-468 RuboCop Categorization
  lib/inquisition/rubocop.rb
  lib/inquisition/rubocop/categorizer.rb
  lib/inquisition/rubocop/issue.rb
  lib/inquisition/rubocop/runner.rb
  spec/fixtures/files/rubocop.yml
  spec/inquisition/rubocop/categorizer_spec.rb
  spec/inquisition/rubocop/issue_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
Labels: FEATURE, REVIEWED

#107 PEO-353 Update Traceroute
  lib/inquisition/traceroute/runner.rb
  spec/dummy/config/routes.rb
  spec/fixtures/files/traceroute.yml
  spec/inquisition/traceroute/runner_spec.rb
  spec/support/shared_examples/runner.rb
Labels: WIP

#108 PEO-319 Update Bundler Audit analyzer
  lib/inquisition.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  spec/dummy/Gemfile.lock
  spec/fixtures/files/bundler_audit.yml
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/bundler/audit/vulnerability_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
Labels: WIP

#102 PEO-472 Rails best practices Categorization
  lib/inquisition.rb
  lib/inquisition/rails_best_practices/categorizer.rb
  lib/inquisition/rails_best_practices/issue.rb
  lib/inquisition/rails_best_practices/runner.rb
  spec/fixtures/files/rails_best_practices.yml
  spec/inquisition/rails_best_practices/categorizer_spec.rb
  spec/inquisition/rails_best_practices/issue_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
Labels: FEATURE, NEED REVIEW

#109 Update lol-dba analyzer
  lib/inquisition.rb
  lib/inquisition/lol_dba/missing_index.rb
  lib/inquisition/lol_dba/runner.rb
  lib/inquisition/traceroute/runner.rb
  spec/dummy/app/models/project.rb
  spec/dummy/app/models/user.rb
  spec/dummy/db/migrate/20190801142755_create_users.rb
  spec/dummy/db/migrate/20190801142756_create_projects.rb
  spec/fixtures/files/active_record_doctor.yml
  spec/fixtures/files/lol_dba.yml
  spec/fixtures/files/rails_best_practices.yml
  spec/fixtures/files/rubocop.yml
  spec/fixtures/files/rubycritic.yml
  spec/inquisition/lol_dba/missing_index_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/support/shared_examples/runner.rb
Labels: NEED REVIEW

#93 PEO-462 Categorization
  .reek.yml
  .rubocop.yml
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/issue.rb
  lib/inquisition/active_record_doctor/runner.rb
  lib/inquisition/brakeman/vulnerability.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  lib/inquisition/category.rb
  lib/inquisition/factory_bot/runner.rb
  lib/inquisition/fasterer/runner.rb
  lib/inquisition/i18n_tasks/runner.rb
  lib/inquisition/issue.rb
  lib/inquisition/lol_dba/missing_index.rb
  lib/inquisition/rails_best_practices/categorizer.rb
  lib/inquisition/rails_best_practices/issue.rb
  lib/inquisition/rails_best_practices/runner.rb
  lib/inquisition/rubocop.rb
  lib/inquisition/rubocop/categorizer.rb
  lib/inquisition/rubocop/issue.rb
  lib/inquisition/rubocop/runner.rb
  lib/inquisition/rubycritic/runner.rb
  lib/inquisition/traceroute/runner.rb
  spec/dummy/.inquisition.yml
  spec/fixtures/files/active_record_doctor.yml
  spec/fixtures/files/brakeman.yml
  spec/fixtures/files/bundler_audit.yml
  spec/fixtures/files/factory_bot.yml
  spec/fixtures/files/fasterer.yml
  spec/fixtures/files/i18n_tasks.yml
  spec/fixtures/files/lol_dba.yml
  spec/fixtures/files/rails_best_practices.yml
  spec/fixtures/files/rubocop.yml
  spec/fixtures/files/rubycritic.yml
  spec/fixtures/files/traceroute.yml
  spec/inquisition/active_record_doctor/issue_spec.rb
  spec/inquisition/active_record_doctor/runner_spec.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/brakeman/vulnerability_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/category_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/inquisition/issue_spec.rb
  spec/inquisition/lol_dba/missing_index_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/rails_best_practices/categorizer_spec.rb
  spec/inquisition/rails_best_practices/issue_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/categorizer_spec.rb
  spec/inquisition/rubocop/issue_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
  spec/support/shared_examples/runner.rb
Labels: FEATURE, REVIEWED

#112 PEO-430 Update RBP analyzer
  config/rails_best_practices/config.yml
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/issue.rb
  lib/inquisition/brakeman/vulnerability.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  lib/inquisition/factory_bot/runner.rb
  lib/inquisition/fasterer/runner.rb
  lib/inquisition/i18n_tasks/runner.rb
  lib/inquisition/lol_dba/missing_index.rb
  lib/inquisition/rails_best_practices/runner.rb
  lib/inquisition/rails_best_practices/warning.rb
  lib/inquisition/rubocop/issue.rb
  lib/inquisition/rubycritic/runner.rb
  lib/inquisition/traceroute/runner.rb
  spec/dummy/config/rails_best_practices.yml
  spec/fixtures/files/rails_best_practices.yml
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/inquisition/issue_spec.rb
  spec/inquisition/lol_dba/missing_index_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/rails_best_practices/issue_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rails_best_practices/warning_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
Labels: NEED REVIEW, ✓ DK

#111 PEO-351 Update rubycritic analyzer
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/runner.rb
  lib/inquisition/brakeman/vulnerability.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  lib/inquisition/factory_bot/runner.rb
  lib/inquisition/fasterer/runner.rb
  lib/inquisition/i18n_tasks/runner.rb
  lib/inquisition/rails_best_practices/categorizer.rb
  lib/inquisition/rubocop/categorizer.rb
  lib/inquisition/rubycritic/analysers/flay.rb
  lib/inquisition/rubycritic/runner.rb
  lib/inquisition/rubycritic/smell.rb
  spec/fixtures/files/rubycritic.yml
  spec/inquisition/active_record_doctor/runner_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/inquisition/issue_spec.rb
  spec/inquisition/lol_dba/missing_index_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/rubocop/categorizer_spec.rb
  spec/inquisition/rubocop/issue_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/analysers/flay_spec.rb
  spec/inquisition/rubycritic/analysers/flog_spec.rb
  spec/inquisition/rubycritic/analysers/reek_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/rubycritic/smell_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
Labels: REVIEWED, ✓ DK

#113 PEO-457 Fix CodeClimate issues
  .reek.yml
  .rubocop.yml
  lib/inquisition/rubocop/rubocop_modified_runner.rb
  lib/inquisition/rubocop/runner.rb
  spec/inquisition/lol_dba/missing_index_spec.rb
  spec/inquisition/outputter_spec.rb
  spec/inquisition/rubocop/rubocop_modified_runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/smell_spec.rb
  spec/inquisition/tasks/inquisition_spec.rb
  spec/support/shred_contexts/rake.rb
  spec/support/task_example_group.rb
Labels: BUGFIX, WIP

#110 PEO-508 Implement bundler-leak runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/bundler/leak/runner.rb
  lib/inquisition/bundler/leak/vulnerability.rb
  spec/dummy/Gemfile.lock
  spec/fixtures/files/bundler_leak.yml
  spec/inquisition/bundler/leak/runner_spec.rb
  spec/inquisition/bundler/leak/vulnerability_spec.rb
  spec/integration/bundler_leak/runner_spec.rb
Labels: FEATURE, REVIEWED

#114 PEO-522 Update versions for each gem runner
  .codeclimate.yml
  .rubocop.yml
  .simplecov
  inquisition.gemspec
Labels: FEATURE, REVIEWED

#117 PEO-521 Update initialize executor
  .reek.yml
  lib/inquisition.rb
  lib/inquisition/badge.rb
  lib/inquisition/configuration.rb
  lib/inquisition/executor.rb
  lib/inquisition/ext/deep_symbolize_keys.rb
  lib/inquisition/init_config.rb
  lib/inquisition/options.rb
  lib/inquisition/runner.rb
  spec/inquisition/active_record_doctor/runner_spec.rb
  spec/inquisition/badge_spec.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/bundler/leak/runner_spec.rb
  spec/inquisition/collector_spec.rb
  spec/inquisition/configuration_spec.rb
  spec/inquisition/executor_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/inquisition/init_config_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/options_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/runner_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
  spec/support/shared_examples/enablable.rb
Labels: WIP

#115 PEO-521 Add --init executor
  .reek.yml
  lib/inquisition/badge.rb
  lib/inquisition/configuration.rb
  lib/inquisition/executor.rb
  lib/inquisition/ext/deep_symbolize_keys.rb
  lib/inquisition/options.rb
  lib/inquisition/runner.rb
  spec/inquisition/active_record_doctor/runner_spec.rb
  spec/inquisition/badge_spec.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/bundler/leak/runner_spec.rb
  spec/inquisition/collector_spec.rb
  spec/inquisition/configuration_spec.rb
  spec/inquisition/executor_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/options_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/runner_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
  spec/support/shared_examples/enablable.rb
Labels: FEATURE, NEED REVIEW
