Repository rubygarage/inquisition, pull requests merged in 2019-08, with the labels that each got.

#60 PEO-302 Update CircleCI configuration
  .circleci/config.yml
  README.md
Labels: NEED REVIEW, ✓ DK, ✓ RY

#72 PEO-364 Update Issue class
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/runner.rb
  lib/inquisition/brakeman/runner.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/fasterer/runner.rb
  lib/inquisition/issue.rb
  lib/inquisition/lol_dba/runner.rb
  lib/inquisition/rails_best_practices/runner.rb
  lib/inquisition/rubocop/runner.rb
  lib/inquisition/rubycritic/runner.rb
  lib/inquisition/severity.rb
  lib/inquisition/traceroute/runner.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/issue_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/severity_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SS

#71 PEO-354 Add the ability to turn on/off a runner
  lib/inquisition.rb
  lib/inquisition/active_record_doctor/runner.rb
  lib/inquisition/badge.rb
  lib/inquisition/brakeman/runner.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/collector.rb
  lib/inquisition/fasterer/runner.rb
  lib/inquisition/lol_dba/runner.rb
  lib/inquisition/rails_best_practices/runner.rb
  lib/inquisition/rubocop/rubocop_modified_runner.rb
  lib/inquisition/rubocop/runner.rb
  lib/inquisition/rubycritic/runner.rb
  lib/inquisition/runner.rb
  spec/inquisition/active_record_doctor/runner_spec.rb
  spec/inquisition/badge_spec.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/collector_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/rubocop_modified_runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/runner_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
  spec/support/.keep
  spec/support/shared_examples/enablable.rb
Labels: FEATURE, NEED REVIEW

#78 PEO-392 Remove unnecessary logging
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/rails_best_practices/runner.rb
Labels: BUGFIX, REVIEWED

#79 PEO-318 Update Brakeman executor
  lib/inquisition.rb
  lib/inquisition/brakeman/runner.rb
  lib/inquisition/brakeman/vulnerability.rb
  lib/inquisition/runner.rb
  lib/inquisition/severity.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/brakeman/vulnerability_spec.rb
  spec/inquisition/configuration_spec.rb
Labels: NEED REVIEW, ✓ DK, ✓ RY

#75 PEO-369 Update rubocop runner
  .rubocop.yml
  config/rubocop/config.yml
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/rubocop.rb
  lib/inquisition/rubocop/rubocop_modified_runner.rb
  lib/inquisition/rubocop/runner.rb
  spec/inquisition/rubocop/rubocop_modified_runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubocop_spec.rb
  spec/inquisition_spec.rb
Labels: FEATURE, WIP, ✓ SS

#77 PEO-371 Implement factory_bot runner
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/factory_bot/factory_bot_modified_linter.rb
  lib/inquisition/factory_bot/runner.rb
  spec/inquisition/factory_bot/factory_bot_modified_linter_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
Labels: FEATURE, WIP

#82 PEO-412 Wrap or convert thor commands into a rake tasks
  Rakefile
  exe/inquisition
  inquisition.gemspec
  lib/inquisition/cli.rb
  lib/inquisition/railtie.rb
  lib/inquisition/tasks/inquisition.rake
  spec/inquisition/cli_spec.rb
  spec/inquisition/tasks/inquisition_spec.rb
  spec/support/shred_contexts/rake.rb
Labels: FEATURE, NEED REVIEW, ✓ RY

#76 PEO-365 Setup E2E tests
  .circleci/config.yml
  .gitignore
  lib/inquisition/brakeman/runner.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/fasterer/runner.rb
  lib/inquisition/lol_dba/runner.rb
  lib/inquisition/rails_best_practices/runner.rb
  lib/inquisition/rubocop/rubocop_modified_runner.rb
  lib/inquisition/rubocop/runner.rb
  lib/inquisition/rubycritic/runner.rb
  spec/dummy/.fasterer.yml
  spec/dummy/Gemfile.lock
  spec/dummy/app/controllers/application_controller.rb
  spec/dummy/config/environments/test.rb
  spec/dummy/config/rails_best_practices.yml
  spec/dummy/config/routes.rb
  spec/dummy/db/migrate/20190801142754_create_active_storage_tables.active_storage.rb
  spec/dummy/db/schema.rb
  spec/fixtures/.keep
  spec/fixtures/files/active_record_doctor.yml
  spec/fixtures/files/brakeman.yml
  spec/fixtures/files/bundler_audit.yml
  spec/fixtures/files/fasterer.yml
  spec/fixtures/files/lol_dba.yml
  spec/fixtures/files/rails_best_practices.yml
  spec/fixtures/files/rubocop.yml
  spec/fixtures/files/rubycritic.yml
  spec/fixtures/files/traceroute.yml
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/brakeman/vulnerability_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/rubocop_modified_runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/integration/active_record_doctor/runner_spec.rb
  spec/integration/brakeman/runner_spec.rb
  spec/integration/bundler_audit/runner_spec.rb
  spec/integration/fasterer/runner_spec.rb
  spec/integration/lol_dba/runner_spec.rb
  spec/integration/rails_best_practices/runner_spec.rb
  spec/integration/rubocop/runner_spec.rb
  spec/integration/rubycritic/runner_spec.rb
  spec/integration/traceroute/runner_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/runner.rb
Labels: FEATURE, NEED REVIEW

#88 PEO-430 Update rails_best_practices runner
  config/rails_best_practices/config.yml
  lib/inquisition/rails_best_practices/runner.rb
  spec/dummy/app/views/layouts/application.html.erb
  spec/fixtures/files/rails_best_practices.yml
  spec/inquisition/rails_best_practices/runner_spec.rb
Labels: FEATURE, NEED REVIEW

#84 PEO-429 Update fasterer config runner
  config/fasterer/config.yml
  lib/inquisition/fasterer/config.rb
  lib/inquisition/fasterer/file_traverser.rb
  lib/inquisition/fasterer/runner.rb
  spec/inquisition/fasterer/config_spec.rb
  spec/inquisition/fasterer/file_traverser_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
Labels: FEATURE, NEED REVIEW

#90 PEO-456 Create Category
  lib/inquisition.rb
  lib/inquisition/category.rb
  spec/inquisition/category_spec.rb
Labels: FEATURE, NEED REVIEW, ✓ SS

#91 PEO-442 Set up SB Admin 2
  lib/inquisition/formatters/html/assets/css/sb-admin-2.min.css
  lib/inquisition/formatters/html/assets/img/.keep
  lib/inquisition/formatters/html/assets/js/sb-admin-2.min.js
  lib/inquisition/formatters/html/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
  lib/inquisition/formatters/html/assets/vendor/chart.js/Chart.min.js
  lib/inquisition/formatters/html/assets/vendor/fontawesome-free/css/all.min.css
  lib/inquisition/formatters/html/assets/vendor/jquery-easing/jquery.easing.min.js
  lib/inquisition/formatters/html/assets/vendor/jquery/jquery.min.js
  spec/inquisition/formatters/html_formatter_spec.rb
Labels: REVIEWED

#96 PEO-465 Fasterer Categorization
  lib/inquisition/fasterer/runner.rb
  spec/fixtures/files/fasterer.yml
  spec/inquisition/fasterer/runner_spec.rb
Labels: FEATURE, REVIEWED

#97 PEO-466 Traceroute Categorization
  lib/inquisition/traceroute/runner.rb
  spec/fixtures/files/traceroute.yml
  spec/inquisition/traceroute/runner_spec.rb
Labels: FEATURE, REVIEWED

#98 PEO-467 Lol Dba Categorization
  lib/inquisition/lol_dba/runner.rb
  spec/fixtures/files/lol_dba.yml
  spec/inquisition/lol_dba/runner_spec.rb
Labels: FEATURE, REVIEWED

#99 PEO-470 Factory Bot Categorization
  lib/inquisition/factory_bot/runner.rb
  spec/inquisition/factory_bot/runner_spec.rb
Labels: FEATURE, REVIEWED

#83 PEO-370 Implement i18n-tasks runner and add tests
  config/i18n_tasks/config.yml
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/i18n_tasks/runner.rb
  spec/dummy/.inquisition.yml
  spec/dummy/app/controllers/application_controller.rb
  spec/dummy/config/locales/en.yml
  spec/fixtures/files/i18n_tasks.yml
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/integration/i18n_tasks/runner_spec.rb
Labels: FEATURE, REVIEWED, ✓ SS

#100 PEO-469 Rubycritic Categorization
  lib/inquisition/rubycritic/runner.rb
  spec/fixtures/files/rubycritic.yml
  spec/inquisition/rubycritic/runner_spec.rb
Labels: FEATURE, REVIEWED

#95 PEO-464 Brakeman Categorization
  lib/inquisition/brakeman/vulnerability.rb
  spec/fixtures/files/brakeman.yml
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/brakeman/vulnerability_spec.rb
Labels: FEATURE, REVIEWED
