Repository rubygarage/inquisition, pull requests merged in 2019-12, with the labels that each got.

#120 Feature | PEO-825 | Generate skeleton of the document
  inquisition.gemspec
  lib/inquisition/outputter/documentation.rb
  lib/inquisition/outputter/presenters/documentation_presenter.rb
  spec/fixtures/files/rails_best_practices.yml
  spec/inquisition/outputter/documentation_spec.rb
  views/documentation_word.rhtml
Labels: NEED REVIEW

#123 Feature | PEO-837 | Add the ability to generate xlsx outputter
  inquisition.gemspec
  lib/inquisition/outputter.rb
  lib/inquisition/outputter/xlsx.rb
  lib/inquisition/outputter/xlsx/builder.rb
  spec/inquisition/outputter/xlsx/builder_spec.rb
  spec/inquisition/outputter/xlsx_spec.rb
Labels: NEED REVIEW

#128 PEO-826 Create Doc outputter skeleton
  inquisition.gemspec
  lib/inquisition.rb
  lib/inquisition/outputter/doc/builder.rb
  lib/inquisition/outputter/doc/file.rb
  lib/inquisition/outputter/doc/home.rb
  lib/inquisition/outputter/doc/layout.rb
  lib/inquisition/outputter/doc/template.rb
  lib/inquisition/outputter/xlsx/builder.rb
  spec/inquisition/outputter/doc/home_spec.rb
  spec/inquisition/outputter/doc/layout_spec.rb
  spec/inquisition/outputter/doc/template_spec.rb
  spec/inquisition_spec.rb
  spec/support/config/timecop.rb
  views/doc/home.rhtml
  views/doc/layout.rhtml
Labels: REVIEWED, ✓RY

#129 Feature | PEO-828 | Fill patch-level verification section
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  lib/inquisition/outputter/doc/gem_details.rb
  lib/inquisition/outputter/doc/templates/base_template.rb
  lib/inquisition/outputter/doc/templates/brakeman.rb
  lib/inquisition/outputter/doc/templates/layout.rb
  lib/inquisition/outputter/doc/templates/patch_level_verification.rb
  lib/inquisition/outputter/doc/templates/technology_stack_scan.rb
  spec/inquisition/bundler/audit/vulnerability_spec.rb
  spec/inquisition/outputter/doc/templates/base_template_spec.rb
  spec/inquisition/outputter/doc/templates/brakeman_spec.rb
  spec/inquisition/outputter/doc/templates/patch_level_verification_spec.rb
  spec/inquisition/outputter/doc/templates/technology_stack_scan_spec.rb
  views/doc/layout.rhtml
  views/doc/patch_level_verification.rhtml
Labels: NEED REVIEW

#124 Feature | PEO-827 | Fill brakeman section
  lib/inquisition/badge.rb
  lib/inquisition/brakeman/vulnerability.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  lib/inquisition/issue.rb
  lib/inquisition/outputter/doc/builder.rb
  lib/inquisition/outputter/doc/gem_details.rb
  lib/inquisition/outputter/doc/templates/base_template.rb
  lib/inquisition/outputter/doc/templates/brakeman.rb
  lib/inquisition/outputter/doc/templates/layout.rb
  lib/inquisition/outputter/doc/templates/patch_level_verification.rb
  lib/inquisition/outputter/doc/templates/technology_stack_scan.rb
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/brakeman/vulnerability_spec.rb
  spec/inquisition/bundler/audit/runner_spec.rb
  spec/inquisition/bundler/audit/vulnerability_spec.rb
  spec/inquisition/bundler/leak/runner_spec.rb
  spec/inquisition/factory_bot/runner_spec.rb
  spec/inquisition/fasterer/runner_spec.rb
  spec/inquisition/i18n_tasks/runner_spec.rb
  spec/inquisition/issue_spec.rb
  spec/inquisition/lol_dba/runner_spec.rb
  spec/inquisition/outputter/doc/templates/base_template_spec.rb
  spec/inquisition/outputter/doc/templates/brakeman_spec.rb
  spec/inquisition/outputter/doc/templates/layout_spec.rb
  spec/inquisition/outputter/doc/templates/patch_level_verification_spec.rb
  spec/inquisition/outputter/doc/templates/technology_stack_scan_spec.rb
  spec/inquisition/outputter/html/builder_spec.rb
  spec/inquisition/outputter/html/overview/by_category_spec.rb
  spec/inquisition/outputter/html/overview/by_executor_spec.rb
  spec/inquisition/outputter/html/overview/by_severity_spec.rb
  spec/inquisition/rails_best_practices/runner_spec.rb
  spec/inquisition/rubocop/runner_spec.rb
  spec/inquisition/rubycritic/runner_spec.rb
  spec/inquisition/traceroute/runner_spec.rb
  spec/support/shared_examples/runner.rb
  views/doc/brakeman.rhtml
  views/doc/layout.rhtml
  views/doc/patch_level_verification.rhtml
Labels: NEED REVIEW

#135 Feature | PEO-126 | Fix bundler and brakeman
  .rubocop.yml
  config/rubocop/config.yml
  lib/inquisition/brakeman/vulnerability.rb
  lib/inquisition/bundler/audit/runner.rb
  lib/inquisition/bundler/audit/vulnerability.rb
  lib/inquisition/issue.rb
  spec/fixtures/files/bundler_audit.yml
  spec/inquisition/brakeman/runner_spec.rb
  spec/inquisition/brakeman/vulnerability_spec.rb
  spec/inquisition/bundler/audit/vulnerability_spec.rb
Labels: NEED REVIEW

#136 Feature | PEO-826 | Add templates with view layout and tests
  lib/inquisition/outputter/doc/builder.rb
  lib/inquisition/outputter/doc/home.rb
  lib/inquisition/outputter/doc/layout.rb
  lib/inquisition/outputter/doc/tpl/base.rb
  lib/inquisition/outputter/doc/tpl/home.rb
  lib/inquisition/outputter/doc/tpl/layout.rb
  lib/inquisition/outputter/doc/tpl/stack.rb
  spec/inquisition/outputter/doc/layout_spec.rb
  spec/inquisition/outputter/doc/template_spec.rb
  spec/inquisition/outputter/doc/tpl/home_spec.rb
  spec/inquisition/outputter/doc/tpl/layout_spec.rb
  spec/inquisition/outputter/doc/tpl/stack_spec.rb
  views/doc/layout.rhtml
  views/doc/stack.rhtml
Labels: NEED REVIEW

#122 Feature | PEO-826 | Fill technology stack section
  Gemfile
  lib/inquisition/outputter/doc/builder.rb
  lib/inquisition/outputter/doc/tpl/layout.rb
  lib/inquisition/outputter/doc/tpl/security.rb
  lib/inquisition/outputter/doc/tpl/security/brakeman.rb
  lib/inquisition/outputter/doc/tpl/security/collector.rb
  lib/inquisition/outputter/doc/tpl/security/patch_level.rb
  lib/inquisition/outputter/doc/tpl/stack.rb
  lib/inquisition/outputter/doc/tpl/stack/collector.rb
  lib/inquisition/outputter/doc/tpl/stack/exception.rb
  lib/inquisition/outputter/doc/tpl/stack/instrumentation.rb
  lib/inquisition/outputter/doc/tpl/stack/jobs.rb
  spec/inquisition/outputter/doc/tpl/home_spec.rb
  spec/inquisition/outputter/doc/tpl/layout_spec.rb
  spec/inquisition/outputter/doc/tpl/security/brakeman_spec.rb
  spec/inquisition/outputter/doc/tpl/security/collection_spec.rb
  spec/inquisition/outputter/doc/tpl/security/collector_spec.rb
  spec/inquisition/outputter/doc/tpl/security/patch_level_spec.rb
  spec/inquisition/outputter/doc/tpl/security_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/collector_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/exception_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/instrumentation_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/jobs_spec.rb
  spec/inquisition/outputter/doc/tpl/stack_spec.rb
  spec/support/shared_examples/collection.rb
  spec/support/shared_examples/empty.rb
  spec/support/shared_examples/produce.rb
  views/doc/layout.rhtml
  views/doc/security.rhtml
  views/doc/security/brakeman.rhtml
  views/doc/security/patch_level.rhtml
  views/doc/stack.rhtml
  views/doc/stack/exception_and_instrumentation.rhtml
  views/doc/stack/jobs.rhtml
  views/doc/stack/monitoring.rhtml
Labels: WIP

#138 Update specs for Stack and Security sections
  lib/inquisition/outputter/doc/tpl/security.rb
  lib/inquisition/outputter/doc/tpl/security/patch_level.rb
  lib/inquisition/outputter/doc/tpl/stack.rb
  public/application.css
  public/application.js
  public/webfonts/fa-solid-900.eot
  public/webfonts/fa-solid-900.svg
  public/webfonts/fa-solid-900.ttf
  public/webfonts/fa-solid-900.woff
  public/webfonts/fa-solid-900.woff2
  spec/inquisition/outputter/doc/tpl/home_spec.rb
  spec/inquisition/outputter/doc/tpl/layout_spec.rb
  spec/inquisition/outputter/doc/tpl/security/brakeman_spec.rb
  spec/inquisition/outputter/doc/tpl/security/patch_level_spec.rb
  spec/inquisition/outputter/doc/tpl/security_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/collector_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/exception_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/instrumentation_spec.rb
  spec/inquisition/outputter/doc/tpl/stack/jobs_spec.rb
  spec/inquisition/outputter/doc/tpl/stack_spec.rb
  spec/support/shared_examples/collection.rb
  spec/support/shared_examples/empty.rb
  spec/support/shared_examples/produce.rb
  spec/support/shared_examples/produceable.rb
  views/doc/stack.rhtml
  views/doc/stack/exception.rhtml
  views/doc/stack/exception_and_instrumentation.rhtml
  views/doc/stack/instrumentation.rhtml
Labels: ✓RY
